### ISSUE TITLE
Cambios en clase "BankAccountManagementSystem", implementación del patrón Strategy.

### ISSUE THREAD

**Issue by jcarrome** [Kalutu/java-projects-for-everybody#4]
He implementado el patrón de diseño Strategy para la validación de transacciones en el sistema de gestión de cuentas bancarias. 
Antes de la implementación, la validación de transacciones estaba directamente en el método "withdraw()" de la clase "BankAccountManagementSystem". Esto causaba que la clase fuera más difícil de modificar y extender en el futuro.
Con el patrón Strategy, la validación de transacciones es delegada a una interfaz "TransactionValidationStrategy", permitiendo que diferentes estrategias de validación sean intercambiadas fácilmente sin modificar el código de la clase "BankAccountManagementSystem".

Objetivo:
Aplicar el patrón Strategy para mejorar la extensión y mantenibilidad del código.
Implicaciones:
Esto permite agregar nuevas estrategias de validación de forma flexible sin necesidad de cambiar la lógica en la clase "BankAccountManagementSystem". Además, facilita las pruebas y la reutilización de código.
![image](https://github.com/user-attachments/assets/5cefd2ee-244c-4882-8196-2fcc3fda31e6)

**Comment by ivoneiman** [comment]
La separación de la lógica de validación en estrategias independientes también facilita las pruebas unitarias. Ahora es posible probar cada estrategia de validación de manera aislada, sin necesidad de realizar pruebas en la clase BankAccountManagementSystem completa. Esto mejora la calidad y la confiabilidad del código. Una posible mejora sería incluir una fábrica de estrategias de validación, de modo que la selección de la estrategia correcta se realice automáticamente en función de ciertos parámetros, como el tipo de cuenta o el monto de la transacción. Esto podría reducir aún más la complejidad y mejorar la cohesión del sistema.
