### ISSUE TITLE
Cambios respecto al uso de las clase Pago e Inventario, aplicando el patron Facade

### ISSUE THREAD

**Issue by LeonardoGino31** [Kalutu/java-projects-for-everybody#8]
Los sistemas, por lo general, deberían priorizar el establecimiento de interfaces sencillas e intuitivas para el usuario, evitando en la medida de lo posible el contacto directo con elementos específicos del sistema. Implementar el patrón de diseño Facade reduce la carga cognitiva y facilita el uso del sistema mediante operaciones más simples.
![image](https://github.com/user-attachments/assets/f14db004-b02b-40bc-8b2f-77640d00ccc0)

**Comment by ivoneiman** [comment]
El Facade centraliza la lógica de negocio relacionada con el pago y el inventario en una sola clase, lo que reduce la necesidad de que otros componentes del sistema accedan directamente a las clases Pago e Inventario. Esto hace que el sistema sea más fácil de mantener y extiende las capacidades sin necesidad de modificar los detalles internos de cada uno de esos componentes. Además,  si se requiere agregar más funcionalidades, como otros métodos de pago o nuevas estrategias de gestión de inventario, el Facade actúa como un punto único de entrada, y se pueden agregar nuevas opciones sin afectar a los usuarios ni a otras partes del sistema
